CREATE SCHEMA IF NOT EXISTS news;
CREATE TABLE IF NOT EXISTS news.user
(
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    roles TEXT[]
);

INSERT INTO news.user (name, email, password, roles)
VALUES
    ('admin', 'admin@mail.ru', '$2a$12$O5zSTqcrOUaa8ScwwDlALekHDZ0Xhe8NFuhjlBjD7f0zN/xcvcIcu', '{"ROLE_ADMIN"}'),
    ('user', 'user@mail.ru', '$2a$12$hJX/z2gdS/uGMbuBc/6nD.Pc/KuEMFyFLYcQrAQPgGuRpX0xlrwCG', '{"ROLE_USER"}'),
    ('moderator', 'moderator@mail.ru', '$2a$12$FFGrwwF/p8TnxIWc1yP5NOy37b.6WjBNCm42z/Z5yRZRAtlHKsDk6', '{"ROLE_MODERATOR"}');
