spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      schema: news
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update